# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bernabe Vega
title: Attempt of sysadmin
email: bernabe@beroth.moe
website: https://beroth.moe

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: don't
#github_username:  b3rosu
minecraft_server: beroth.moe
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: gitea
    icon: fas fa-git
    url: https://git.beroth.moe
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi I'm Bernabe and I'm open to work, I've been working in IT for over three years, two of them as a developer.
  I like to never stop learning and try to always try new things and take advantage with code.
  I have experience working with Linux and Windows servers but what I like the most is Linux.
  I am most skilled in: <mark>Linux</mark>, <mark>JavaScript</mark> & <mark>networking</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My self hosted stuff
        link: beroth.moe
        # link_text: Project Website
        #additional_links:
        # - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I use arch BTW (debian for servers I'm not crazy 🥴)
        description: | # this will include new lines to allow paragraphs
          I started to rent my first VPS in 2023 for <mark>Server administration class</mark> and after that I've keep doing it. 
          The things I currently host and host for a while are:
            - Email whit exim & dovecot, currently with poste.io
            - Proxys with nginx apache (with SSL of curse)
            - OpenVPN & Wireguard VPN
            - ShadowSocks tunnel proxy (to jump the CUCEI firewall 👻)
            - A PBX with asterisk and issabel (no longer do this)
            - Minecraft servers
            - Matrix (no longer active)
            - FTP with proftpd (no longer active)
            - PiHole + Unbound
            - CopyParty
            - Immich
            - N8N and Gitea with postgres
            - Vaultwarden
            - Excalidraw

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Moti Digital
          #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: IT intern
        caption: 2024 - Present
        quote: >
          Started as Intert, then IT analist, then IT leader, then ERP Leader which is my current position
        description: | # this will include new lines to allow paragraphs
          I develop internal tools for the company in a unified system with simplified UI and custom business logic
          Mainly with ReactJS and Bun with express, both with vanilla JS

      - layout: left
        title: Centro empresarial de Jalisco S.P.
          #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: IT intern
        caption: January 2023 - 2024
        quote: >
          Solving 21st century problems by restarting the server
        description: | # this will include new lines to allow paragraphs
          I help people with IT related problems, also I manage the servers which is the funiest part.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CUCEI
        caption: 2021 - 2026
        sub_title: BSc software engineering
        #quote: >
          #the quote that will come to my mind.
        description: | # this will include new lines to allow paragraphs
          I really like my career, and like to study in the library but only the thing that interest me.

  - title: Badges & Courses
    layout: text
    content: |
      
      ![DockerEssentials](/images/docker-essentials-badge.png "Docker essentials course badge")
      ![Cybersecurity](/images/cybersecurity.png "Cisco introduction to cybersecurity badge")

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my interests are:
      - Gaming
      - Tiling window managers xd
      - Manga & anime


# Footer
footer_show_references: true
# references_title: References on request (Override references text)
references_title: . 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
